local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0 #before 5.0
  publish_frequency: 2.0 #before 2.0
  static_map: false
  rolling_window: true
  width: 2.5 
  height: 2.5
  resolution: 0.05 #increase to for higher res 0.025
  transform_tolerance: 0.5
  cost_scaling_factor: 12
  inflation_radius: .1
  plugins:
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
    - {name: 2d_obstacles_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: 3d_obstacles_layer,  type: "costmap_2d::VoxelLayer"}
    # - {name: rgbd_obstacle_layer,     type: "spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer"}

