TebLocalPlannerROS:
  
  odom_topic: odom
  map_frame: map

  # Robot

  max_vel_x: 0.4
  max_vel_x_backwards: 0.3
  max_vel_theta: .4 
  max_vel_y: 0.4
  acc_lim_y: 0.4
  acc_lim_x: 0.4
  acc_lim_theta: .3
  min_turning_radius: 0.0
  wheelbase: 0.0
  cmd_angle_instead_rotvel: False
  footprint_model: 
    type: "polygon"
    vertices: [[-0.22,-0.28], [-0.22,0.28], [0.55,0.15], [0.55,-0.15]] 
  
  # GoalTolerance

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05
  free_goal_vel: True
  complete_global_plan: True


  # Trajectory

  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  min_samples: 3
  max_samples: 500
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: False
  max_global_plan_lookahead_dist: 3.0
  global_plan_viapoint_sep: 0.25
  global_plan_prune_distance: 0.50
  exact_arc_length: False
  feasibility_check_no_poses: 10
  publish_feedback: False


  # Obstacles

  min_obstacle_dist: 0.10 
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1
  obstacle_poses_affected: 15
  inflation_dist: 0.1
  legacy_obstacle_association: True
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: True
  costmap_converter_rate: 5


  # Optimization

  no_inner_iterations: 3
  no_outer_iterations: 2
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  obstacle_cost_exponent: 4
  weight_max_vel_x: 2
  weight_max_vel_y: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_y: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1 
  weight_kinematics_forward_drive: 1
  weight_optimaltime: 1
  weight_shortest_path: 0
  weight_obstacle: 10
  weight_inflation: .2
  weight_dynamic_obstacle: 1
  weight_dynamic_obstacle_inflation: 0.2
  weight_viapoint: 1.0
  weight_adapt_factor: 2
  

  # Parallel Planning

  enable_homotopy_class_planning: True
  enable_multithreading: True
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_prefer_initial_plan: 0.9
  selection_obst_cost_scale: 1.0
  selection_alternative_time_cost: False
  
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 5
  roadmap_graph_area_length_scale: 1.0
  h_signature_prescaler: 0.5
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 0.45
  switching_blocking_period: 0.0
  viapoints_all_candidates: True
  delete_detours_backwards: True
  max_ratio_detours_duration_best_duration: 3.0
  visualize_hc_graph: False
  visualize_with_time_as_z_axis_scale: False

  # Recovery

  shrink_horizon_backup: True
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10
